import type { LevelDef } from "./types";

export const LEVELS: LevelDef[] = [
  {
    id: 1,
    name: "Circuito",
    place: "Interior, CDMX",
    blurb: "Tres carriles y acotamiento. Aprende a cambiarte.",
    goal: 8,
    speed: 260,
    traffic: 90,
    spawnDistance: 240,
    doubleChance: 0.18,
    truckChance: 0,
    theme: "day",
  },
  {
    id: 2,
    name: "Periférico",
    place: "Naucalpan",
    blurb: "Curvas y sentido contrario. El acotamiento salva.",
    goal: 12,
    speed: 300,
    traffic: 100,
    spawnDistance: 220,
    doubleChance: 0.28,
    truckChance: 0.08,
    theme: "day",
  },
  {
    id: 3,
    name: "México–Qro",
    place: "Autopista 57",
    blurb: "Curvas más cerradas. Cuidado de frente.",
    goal: 16,
    speed: 340,
    traffic: 110,
    spawnDistance: 200,
    doubleChance: 0.38,
    truckChance: 0.18,
    theme: "dusk",
  },
  {
    id: 4,
    name: "Palmillas",
    place: "Caseta y recta",
    blurb: "Velocidad de crucero. Rebasa con decisión.",
    goal: 20,
    speed: 380,
    traffic: 125,
    spawnDistance: 190,
    doubleChance: 0.46,
    truckChance: 0.24,
    theme: "dusk",
  },
  {
    id: 5,
    name: "Del Sol",
    place: "Cuernavaca",
    blurb: "Noche en la montaña. Mira las luces traseras.",
    goal: 24,
    speed: 410,
    traffic: 135,
    spawnDistance: 180,
    doubleChance: 0.54,
    truckChance: 0.3,
    theme: "night",
  },
  {
    id: 6,
    name: "La 57",
    place: "Nocturna",
    blurb: "Tráfico denso. Un carril siempre queda libre.",
    goal: 28,
    speed: 440,
    traffic: 145,
    spawnDistance: 170,
    doubleChance: 0.6,
    truckChance: 0.34,
    theme: "night",
  },
  {
    id: 7,
    name: "Aguacero",
    place: "Lluvia en la 57",
    blurb: "Pista mojada. El auto resbala un poco al cambiar.",
    goal: 32,
    speed: 420,
    traffic: 130,
    spawnDistance: 175,
    doubleChance: 0.64,
    truckChance: 0.38,
    theme: "rain",
  },
  {
    id: 8,
    name: "Infinito",
    place: "Carrera abierta",
    blurb: "Sin meta. Sobrevive y suma rebasadas.",
    goal: 0,
    speed: 470,
    traffic: 150,
    spawnDistance: 165,
    doubleChance: 0.7,
    truckChance: 0.42,
    theme: "night",
  },
];

export const MAX_SPEED = 560;
